### ISSUE TITLE
url RESOURCE column in datadog traces ui displays "/"

### ISSUE THREAD

**Issue by assafcoh** [DataDog/dd-opentracing-cpp#118]
We use nginx-ingress-controller 0.25.1 on aws eks kubernetes version 1.13.
We use datadog agent 6.15.0.
We configured nginx ingress with this rule (see below) and enabled opentracing with datadog. 
In the datadog APM traces ui we see the nginx traces, but resource column is always "/" instead of the real resource path which is "/test" or "/ping"

```
rule {
      host = "test.example.com"
      http {
        path {
          backend {
            service_name = "cpe-test1"
            service_port = 80
          }
          path = "/"
        }
      }
    }
```

We expect to see the real resource "/test" (or "/ping") not the root path "/".
Note that  if we  create a separate ingress rule for each resource path, it works as expected (i.e. the correct resource url is shown in datadog ui resource column) , but creating ingress rules for each and every resource path is very inconvenient and seems like a tedious workaround.

What can we do in order to see the real resource path in datadog APM traces ui?

**Comment by cgilmour** [comment]
The default value for this comes from nginx, and we effectively only get given the value of `path` from the ingress definition.

There's two ways to override it, but before describing them, it's important to warn about security and cardinality.
- URIs can contain data that some people consider private (eg: auth tokens, tracking identifiers etc), so care must be taken to ensure that data is kept private.
- the resource field should be "low cardinality" (low number of unique values), because of indexing and also lists of resource in the UI. You can use a different tag name to avoid this problem.

The way to override the resource name is to set the `resource.name` tag to a different value, using the `opentracing_tag` directive.

The first way is using `location-snippet` configuration in the `nginx-configuration` configmap. This will apply to all ingresses that get configured.
```json
data:
  enable-opentracing: "true"
  datadog-collector-host: $HOST_IP
  datadog-service-name: "nginx"
  location-snippet: |
    opentracing_trace_locations off;
    opentracing_tag resource.name $uri;
```

The second is essentially the same idea, but via a different mechanism: an annotation on the ingress. This only applies to the specific ingress with the annotation.
```
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      opentracing_trace_locations off;
      opentracing_tag resource.name $uri;
```

**Comment by assafcoh** [comment]
Fantastic! i used the annotation on the ingress and it worked as expected.
Thank you very much for your clear answer!
