### ISSUE TITLE
Can tracing be totally disabled in nginx using an env var?

### ISSUE THREAD

**Issue by kmorkans** [DataDog/dd-opentracing-cpp#155]
Hi

Trying to turn off plugin by setting DD_TRACE_ANALYTICS_ENABLED to false, but the agent is still reporting in and counts toward APM billing.
Couldn't find documentation on how to do this. Please, advise.

**Comment by cgilmour** [comment]
That environment variable only affects the "Trace Analytics" feature, rather than enabling/disabling traces.
You might have wanted `DD_TRACE_ENABLED=false`.

**Comment by dgoffredo** [comment]
Setting `DD_TRACE_ENABLED=false` in the ultimately cases this branch to be skipped: https://github.com/DataDog/dd-opentracing-cpp/blob/e76fc0cc6878d66251652f4add6f32c213b94c67/src/span_buffer.cpp#L135-L137
so that no spans are sent to the agent. This should resolve your issue, kmorkans. Thanks, Caleb.

**Comment by kmorkans-lumoa** [comment]
Hi. Just now got into looking at this again
DD_TRACE_ENABLED=false  maybe doesn't send traces but the module still tried to connect to agent. 
```
Failed to connect to SOMEIP port 8126 after 0 ms: Connection refused
90
error: Error sending traces to agent: Couldn't connect to server
```
I have APM disabled in this env.
Would be nice to be able to run the same nginx conf in environment with APM disabled and not have log full of tracer connection errors.

**Comment by dgoffredo** [comment]
What is your setup with nginx, dd-opentracing-cpp, nginx-opentracing, etc.? What you want might not be possible, but with more details I could look into whether there's a workaround.

**Comment by kmorkans-lumoa** [comment]
Tried both - nginx with dd-opentracing-cpp and now switched to nginx-opentracing image.
I now get around this by having separate conf for prod environment where APM is enabled and having different command in app deployment (k8s). Not ideal because if for some reason opentracing part breaks this might go unnoticed till it hits production.

**Comment by dgoffredo** [comment]
The nginx-opentracing module will load the tracer (and thus try to connect to the agent) if the "opentracing_load_tracer" directive succeeded:

https://github.com/opentracing-contrib/nginx-opentracing/blob/7cd0479699c0ac9bd341a8e2b65c595d7c94d85e/opentracing/src/ngx_http_opentracing_module.cpp#L210-L222

https://github.com/opentracing-contrib/nginx-opentracing/blob/7cd0479699c0ac9bd341a8e2b65c595d7c94d85e/opentracing/src/ngx_http_opentracing_module.cpp#L127-L132

One idea that won't work is to wrap the `opentracing_load_tracer` inside some sort of conditional context. It won't work because `opentracing_load_tracer` can only happen in the main section or in an `http` block, neither of which support `if`, and even if they did, `opentracing_load_tracer` isn't allowed in an `if`, and even if it were, it probably wouldn't work.

The "with tracing" `nginx.conf` and the "without tracing" `nginx.conf` must differ at least by the one line containing `opentracing_load_tracer`.

**Comment by dgoffredo** [comment]
@kmorkans-lumoa [kmorkans-lumoa](https://github.com/kmorkans-lumoa), my colleague just pointed out that what might be causing the error
```
Failed to connect to SOMEIP port 8126 after 0 ms: Connection refused
90
error: Error sending traces to agent: Couldn't connect to server
```
is a failure of the `DD_TRACE_ENABLED=false` to be forwarded to nginx's worker (child) processes.

If you are using Datadog's tracing plugin in nginx, then the nginx configuration must name all environment variables to forward to worker processes, e.g.
```nginx.conf
env DD_AGENT_HOST;
env DD_ENV;
# This one isn't in our usage examples.
env DD_TRACE_ENABLED;
```
Check whether this silences the error for you.
