### ISSUE TITLE
Missing dependencies for static lib

### ISSUE THREAD

**Issue by AlvaroFS** [DataDog/dd-opentracing-cpp#179]
When creating the static lib, no dependencies are added to that target.

After 
https://github.com/DataDog/dd-opentracing-cpp/blob/443e9e67eae0da1b0ab370b70d6086934627cc65/CMakeLists.txt#L77

the following code should be added:
`target_link_libraries(dd_opentracing-static ${DATADOG_LINK_LIBRARIES})`

**Comment by cgilmour** [comment]
Thanks reporting this, @AlvaroFS, and appreciate the contribution on conan-io/conan-center-index#5532

I think we can both agree that needing a patch is a fragile way to go and a burden to maintain there.
We'll be happy to hear any suggestion you have on that. Specifically about sanitizers, we could handle that differently since they're mainly for this project's maintainers and CI, and not really for users of the project.
