### ISSUE TITLE
NGINX logs using the default logging function are badly mixed with other logs, leading to parsing errors

### ISSUE THREAD

**Issue by aureplop** [DataDog/dd-opentracing-cpp#195]
In our logs at the company I'm working at, I can see sometimes things like this:
![image](https://user-images.githubusercontent.com/21142069/130938009-33359d5a-e587-46d0-b866-608683e9666c.png)
![image](https://user-images.githubusercontent.com/21142069/130938718-724cab33-ff2b-4a9b-b8d1-1fc80d186082.png)

I guess the startup logs are using the default logging function introduced in https://github.com/DataDog/dd-opentracing-cpp/pull/150. And the issue is specifically coming from this line:
https://github.com/DataDog/dd-opentracing-cpp/blob/e76fc0cc6878d66251652f4add6f32c213b94c67/include/datadog/opentracing.h#L125

I'm not a C++ pro, but maybe there is no guarantee that the all pieces ("info:", "message" and EOL) are written to stderr in one shot.
I guess another worker process can succeed to write one or two between the first two for example, to write it's starting or startup log from its own tracer.

This is causing false positives error logs. We already added a custom parser rule to parse logs like `%(level:word): %(message:data)`. But these `info:` being sometimes here twice or more, sometimes not, sometimes on another tracer log, sometimes on a totally different log makes it to hard, I believe we will keep the parsing rule assuming the log is correctly generated.

In the meantime, we are using the env var `DD_TRACE_STARTUP_LOGS: "false"` to turn off the startup logs. Last note for other interested readers: you also need to add `env DD_TRACE_STARTUP_LOGS;` to the main nginx.conf.

**Comment by dgoffredo** [comment]
> I'm not a C++ pro, but maybe there is no guarantee that the all pieces ("info:", "message" and EOL) are written to stderr in one shot.

You're right.  `std::cerr` is unbuffered by default, meaning that each `<<` entails a write to the underlying file.

The logging facilities that were added in the PR that you reference are not used by nginx.

nginx loads our plugin using this function: https://github.com/DataDog/dd-opentracing-cpp/blob/e76fc0cc6878d66251652f4add6f32c213b94c67/src/dynamic_load.cpp#L12

Ideally, nginx would configure the tracer to use `ngx_*` logging functions instead of logging directly to `stderr`. However, the API between the nginx module and its plugins (such as ours) doesn't allow for this.

We know when we are being loaded dynamically, and so we could pick a different default logger in that case, but we could not pick nginx's, because our code is independent of nginx's.

Off the top of my head, I don't know a good solution to this problem.

I've been investigating the possibility of creating a Datadog-specific (or at least different from `nginx-opentracing`) nginx module for tracing.  We could address consistent log formatting there, but that's looking at least a quarter ahead.

**Comment by aureplop** [comment]
Thanks for your reply @dgoffredo! I just went back of vacations and get the opportunity to reply to you.

Do you think the changes in https://github.com/DataDog/dd-opentracing-cpp/pull/200 would be ok and if they would be enough to fix the situation described originally?
