### ISSUE TITLE
Support for ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by kaarolch** [DataDog/dd-opentracing-cpp#238]
Hey 👋 
After upgrade `dd-opentracing-cpp` to version >= `1.3.2` on ubuntu 18.04 during nginx restart we've get error: 
```
nginx: [error] Failed to load tracing library /usr/local/lib/libdd_opentracing.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/local/lib/libdd_opentracing.so)
```
Official bionic repository support `GLIBCXX_3.4.25'. To upgrade it  to get `GLIBCXX_3.4.26` we need to update gcc base on external [PPA repo]9https://askubuntu.com/questions/1140183/install-gcc-9-on-ubuntu-18-04). 
Is there any chance to have a release that would be working with 18.04 LTS without bumping gcc to the newest version?

**Comment by kaarolch** [comment]
We plan to use `1.3.2` to enable: `Introduce DD_TRACE_SAMPLE_RATE and DD_TRACE_RATE_LIMIT sampling controls.`

**Comment by dgoffredo** [comment]
I moved our build image to `ubuntu:20.04` in order to get a version of CMake that supports the "`OBJECT`" type of build target.

Elsewhere I've created build images that compile CMake from source for older systems.  We could do that.

Of course I instead recommend that you move to a newer system, but I know that's not always feasible.

I'll talk to the team about changing our build image and producing another release of binaries that use an older glibc.

**Comment by kaarolch** [comment]
Yep, We would like to bump all of our system but as you mentioned sometimes is not easy to bump all of them in short term, especially when they still have LTS support.

**Comment by dgoffredo** [comment]
https://github.com/DataDog/dd-opentracing-cpp/pull/239

**Comment by dgoffredo** [comment]
https://github.com/DataDog/dd-opentracing-cpp/releases/tag/v1.3.4
