### ISSUE TITLE
Support newer dynamic loading interface

### ISSUE THREAD

**Issue by rnburn** [DataDog/dd-opentracing-cpp#52]
Could you guys upgrade to the newer dynamic loading interface?

I'm looking to make a new release for nginx-opentracing using OpenTracing-1.5.

You can see https://github.com/lightstep/lightstep-tracer-cpp/pull/105 for an example of how the changes can be made.

**Comment by willgittoes-dd** [comment]
Thanks, I didn't do this before since I was waiting for a release of nginx-opentracing first 😅 So my PR also breaks that circular dependency by building nginx-opentracing rather than using a release.

I've run out of time today, and I'm going on a date with wifey - please go ahead with your own upgrade if you are able; I don't mind if it breaks us a bit, I'll get the PR merged tomorrow.

**Comment by willgittoes-dd** [comment]
Release/tag v0.3.0 supports this

https://github.com/DataDog/dd-opentracing-cpp/releases/tag/v0.3.0

**Comment by willgittoes-dd** [comment]
I tried to make things a bit easier for you by updating the existing PR that updates dependencies to include these changes.

https://github.com/opentracing-contrib/nginx-opentracing/pull/62
