### ISSUE TITLE
Cannot set Span's start, duration etc.

### ISSUE THREAD

**Issue by tiendq** [DataDog/dd-opentracing-cpp#88]
I tried to trace like examples in this repo, but problem is `span_a` returned from `StartSpan` is `opentracing::v2::span` and it does't have fields like `start`, `duration` etc.

How could I create and use spans of types `datadog::opentracing::SpanData` which has all data members same as explained [here](https://docs.datadoghq.com/api/?lang=bash#send-traces).
```
 datadog::opentracing::TracerOptions tracer_options{"dd-agent", 8126, "compiled-in example"};
 auto tracer = datadog::opentracing::makeTracer(tracer_options);
 auto span_a = tracer->StartSpan("A");
 span_a->SetTag("tag", 123);
```

**Comment by cgilmour** [comment]
Hi @tiendq 

This tracer implements the OpenTracing API, and the spans automatically capture the start time and duration.
The `datadog::opentracing::DatadogSpan` are created indirectly, and your code would normally interact with them using the OpenTracing methods.

The tracer also encodes and sends the spans to the datadog agent.
You don't need to write the code to do that.

Let me know if that explains what you needed.

**Comment by tiendq** [comment]
Hi @cgilmour,

Thanks for your explanation, I got `span` traced with auto captured time now but I don't know how to set the `error` field. There are Status and Error columns in the Trace List (datadoghq.com), how could I set these fields in a `Span` object?

**Comment by cgilmour** [comment]
You should be able to after some small changes.
First, include the extra header from opentracing.
`#include <opentracing/ext/tags.h>`

Then, set the `error` tag to true when an error condition should be reported.
`span_x->SetTag(opentracing::ext::error, true);`

**Comment by tiendq** [comment]
Thank you, I could mark a Span as error now, but I noticed only Status field changed. I guess column Error is for error message but I didn't see anything about it in the `tags.h`.

**Comment by cgilmour** [comment]
Correct, opentracing does not have standard tags for additional details to an error.

However, datadog recognizes a couple of additional tags.
`error.type`: a general category for the error
`error.msg`: additional detail for the error

An example:
```
    span_x->SetTag(opentracing::ext::error, true);
    span_x->SetTag("error.type", "dns");
    span_x->SetTag("error.msg", "unable to resolve address for x.y.z");
```
When both type and msg are provided, it should appear in the error column.
Otherwise, the message will appear in the span's details.

The value for `error.type` is user-defined, but it helps if they're short, meaningful and consistent within your application(s).

Another way of using these tags is in an exception handler, eg:
```
...
#include <typeinfo>
...

    try {
      ...
    } catch (std::exception& e) {
      span_x->SetTag(opentracing::ext::error, true);
      span_x->SetTag("error.type", typeid(e).name());
      span_x->SetTag("error.msg", e.what());
    }
```
The value that `typeid(e).name()` returns will probably be "mangled", though.

**Comment by tiendq** [comment]
Awesome, it works like a charm :)

Thanks @cgilmour  for your support.
